os: osx

osx_image: xcode9.3

sudo: false

cache: Unity_WebGL.pkg

install:
- sudo -E sh ./scripts/install-dependencies.sh

jobs:
  include:
    - stage: warm up cache
      script: true
    - stage: build app
      script: true
    - stage: run tests
      script: true
    - 
      script: true
    - stage: deploy to staging
      script: true
      if: branch = staging
    - stage: deploy to master
      script: true
      if: branch = master

after_failure:
- cat ./build-job.log

after_success:
- echo "[test log] build succeed"
